export const PROJECT_ITEM_COLUMNS_MAP: Record<string, string> = {
  code: 'ID',
  'item.thumbnail': 'Thumbnail',
  owner: 'Owner',
  group: 'Group',
  division: 'Division',
  site: 'Site',
  cmSite: 'CM Site',
  phase: 'Phase',
  tfsStdPrice: 'TFS Std Price',
  omegaPrice: 'Omega Price',
  'item.ItemCode': 'MFG P/N',
  partNumber: 'Part Number',
  'item.FirmName': 'Manufacturer',
  mfr: 'MFR',
  'item.ItemName': 'Description',
  desc: 'Desc',
  commodities: 'Commodities',
  dateCode: 'DC',
  countryOfOrigin: 'COO',
  lotCode: 'Lot Code',
  palletNo: 'Pallet No',
  siteLocation: 'Site Location',
  subLocation2: 'Sub Location 2',
  subLocation3: 'Sub Location 3',
  dateReceived: 'Date Received',
  dateReceivedBy: 'Date Received By',
  packagingType: 'Packaging Type',
  spq: 'SPQ',
  cost: 'Cost',
  totalStock: 'Total Stock',
  notes: 'Notes',
  availableToOrder: 'Available To Order',
  stockIn: 'Stock-In (In Process)',
  stockOut: 'Stock-Out (Delivered)',
  agingDays: 'Aging Days',
  createdAt: 'Created At',
  updatedAt: 'Updated At',
}

export const DEFAULT_PROJECT_ITEM_HIDDEN_FIELDS = ['group', 'division', 'site', 'cmSite', 'phase', 'tfsStdPrice', 'omegaPrice']
