import {
  AlertCircle,
  Check,
  Construction,
  LoaderCircle,
  LockKeyhole,
  LogIn,
  LogOut,
  MessageSquareText,
  ShieldCheck,
  ShieldClose,
  TriangleAlert,
  X,
  XCircle,
  ClipboardList,
} from 'lucide-react'

export const Icons = {
  spinner: LoaderCircle,
  login: LogIn,
  logout: LogOut,
  check: Check,
  construction: Construction,
  triangleAlert: TriangleAlert,
  shieldCheck: ShieldCheck,
  shieldClose: ShieldClose,
  alertCircle: AlertCircle,
  lockKeyHole: LockKeyhole,
  x: X,
  xCircle: XCircle,
  msgSquareText: MessageSquareText,
  clipboadList: ClipboardList,
}
